---
title: "spain-covid"
author: "Martim"
date: "3/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)
```

## R Markdown

```{r}
x <- seq(1, 60)
casos <- c(4, 10, 14, 26, 34, 59, 85, 121, 166, 228, 401, 525,
       674, 1231, 1695, 2277, 3146, 5232, 6391, 7988,
       9942, 11308)
casos <- casos[1:22]

data_spain <- data.table(x = x,
                   y = casos)
data_spain[x > length(casos), y := NA]

data_spain[, growth := ((y - shift(y))/shift(y)) * 100][x == 1, growth := 0]

inter = mean(data_spain[!is.na(y), growth])

dados <- data_spain[!is.na(y)]

model_logis <- nls(y ~ SSlogis(x, Asym, xmid, scal), data = dados,
     start = c(Asym = 15000, xmid = 18 , scal = 2),
     nls.control(maxiter = 1000,
                 warnOnly = T))
value_logis <- predict(model_logis, data_2)
data_spain[, predic_logis := value_logis]


```


```{r}

```

```{r}
ggplot(data_spain) +
  geom_point(aes(x, y),
             colour = 'blue') +
  geom_line(aes(x, predic_logis))
```


