---
title: "Untitled"
author: "M"
date: "2/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars, echo = F, warning=F}
library(foreign)
library(data.table)
library(ggplot2)


data <- read.spss("/Users/mmosfa/Downloads/APIS0061_basededados.sav",to.data.frame = T)

data <- as.data.table(data)

data[, SEXO]



ggplot(data[, 'SEXO'], aes(x = SEXO)) +
  geom_bar(stat = 'count')

colnames(data)

ggplot(data, aes(Q13d)) +
  geom_bar(stat = 'count') +
  facet_wrap(~SEXO) +
  scale_y_continuous(breaks = seq(0,150,10))

ggplot(data, aes(Q13d)) +
  geom_bar(stat = 'count') +
  facet_wrap(~Q12b) +
  scale_y_continuous(breaks = seq(0,150,10))

ggplot(data, aes(Q13d)) +
  geom_bar(stat = 'count') +
  facet_wrap(~D03,scales = 'free_x') +
  scale_y_continuous(breaks = seq(0,150,10))


ggplot(data, aes(Q13d)) +
  geom_bar(stat = 'count') +
  facet_wrap(~D02,scales = 'free_x') +
  scale_y_continuous(breaks = seq(0,150,10))
Age <- 21

208 - (0.7 * Age)



```
